//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InformaticaEntities : DbContext
    {
        public InformaticaEntities()
            : base("name=InformaticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arca> Arca { get; set; }
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<Computadoras> Computadoras { get; set; }
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<UnidadNegocio> UnidadNegocio { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
