//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computadoras
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Fabricante { get; set; }
        public string serie { get; set; }
        public string modelo { get; set; }
        public string factura { get; set; }
        public string IP { get; set; }
        public string MAC { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Estatus { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string Proveedor { get; set; }
        public string Procesador { get; set; }
        public string Ram { get; set; }
        public string HD { get; set; }
        public string Video { get; set; }
        public string E_S { get; set; }
        public decimal Precio { get; set; }
        public string Madre { get; set; }
    }
}
