//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos
    {
        public int ID { get; set; }
        public int ID_Usuario { get; set; }
        public string Contraseña_mail { get; set; }
        public string Usuario_servidor { get; set; }
        public string Contraseña_servidor { get; set; }
        public string codigo_reloj { get; set; }
        public string NumUsuario_reloj { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
